### ISSUE TITLE
I've got an error message

### ISSUE THREAD

**Issue by Ruehrfisch** [dewiniaid/BlueprintExtensions#16]
Hi there,

the following error message popped up when I tried starting the first level of the Transport Belt Madness-Campaign:

`Error while running event BlueprintExtensions::on_configuration_changed
Invalid surface name: Surface names must not be blank and must be unique.
stack traceback:
	__BlueprintExtensions__/modules/landfill.lua:53: in function 'compute_prototype_overrides'
	__BlueprintExtensions__/modules/landfill.lua:126: in function '?'
	__BlueprintExtensions__/control.lua:60: in function 'call_module_methods'
	__BlueprintExtensions__/control.lua:96: in function <__BlueprintExtensions__/control.lua:93>
stack traceback:
	[C]: in function 'create_surface'
	__BlueprintExtensions__/modules/landfill.lua:53: in function 'compute_prototype_overrides'
	__BlueprintExtensions__/modules/landfill.lua:126: in function '?'
	__BlueprintExtensions__/control.lua:60: in function 'call_module_methods'
	__BlueprintExtensions__/control.lua:96: in function <__BlueprintExtensions__/control.lua:93>`

**Comment by dewiniaid** [comment]
This should be fixed in 0.4.6, which will be out later today.
