### ISSUE TITLE
Getting error on server startup

### ISSUE THREAD

**Issue by sebbi08** [dewiniaid/BlueprintExtensions#19]
aftern an update of the game and mods on my serve. i get the following error

  51.931 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Blueprint Extensions caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlueprintExtensions::on_configuration_changed
Invalid surface name: Surface names must not be blank and must be unique.
stack traceback:
        __BlueprintExtensions__/modules/landfill.lua:53: in function 'compute_prototype_overrides'
        __BlueprintExtensions__/modules/landfill.lua:126: in function '?'
        __BlueprintExtensions__/control.lua:60: in function 'call_module_methods'
        __BlueprintExtensions__/control.lua:96: in function <__BlueprintExtensions__/control.lua:93>
stack traceback:
        [C]: in function 'create_surface'
        __BlueprintExtensions__/modules/landfill.lua:53: in function 'compute_prototype_overrides'
        __BlueprintExtensions__/modules/landfill.lua:126: in function '?'
        __BlueprintExtensions__/control.lua:60: in function 'call_module_methods'
        __BlueprintExtensions__/control.lua:96: in function <__BlueprintExtensions__/control.lua:93>

**Comment by Wyrrrd** [comment]
Looks like a duplicate of #16

**Comment by dewiniaid** [comment]
This should be fixed in version 0.4.6, which will be released later today.
