### ISSUE TITLE
Crashing since 0.2.2

### ISSUE THREAD

**Issue by Omnifarious** [dewiniaid/BlueprintExtensions#2]
A lot of complaints about not being able to find a Util module. There appears to be a util.lua module though. Maybe you mispelled it, or got the case wrong when you checked it in?

I really hate git. Mercurial got this (and so many other things) right. You wouldn't have had this problem with it.

**Comment by dewiniaid** [comment]
Interesting how this never came up in testing.  Are you on Linux perchance?

**Comment by dewiniaid** [comment]
Fixed in now-released 0.2.4
