### ISSUE TITLE
Issue following the update of Electronic Locomotives

### ISSUE THREAD

**Issue by avpas** [dewiniaid/BlueprintExtensions#25]
Hello,

After updating Luzifer_senpai's Electronic Locomotives, I got the following error when I tried to load my game. Please note that there are no electric locomotives in this game (yet).

I am not sure which mod is at fault, so I am contacting the other modder as well.

Thank you!

`The mod Blueprint Extensions caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlueprintExtensions::on_configuration_changed
The mod Electronic Locomotives caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Electronic_Locomotives::on_surface_created (ID 61)
__Electronic_Locomotives__/scripts/Events.lua:220: bad argument #1 of 2 to 'next' (table expected, got nil)
stack traceback:
	[C]: in function 'next'
	__Electronic_Locomotives__/scripts/Events.lua:220: in function 'MainGUIUpdateProviderList'
	__Electronic_Locomotives__/scripts/Events.lua:506: in function 'handler'
	__core__/lualib/event_handler.lua:44: in function <__core__/lualib/event_handler.lua:42>
stack traceback:
	__BlueprintExtensions__/modules/landfill.lua:53: in function 'compute_prototype_overrides'
	__BlueprintExtensions__/modules/landfill.lua:126: in function '?'
	__BlueprintExtensions__/control.lua:60: in function 'call_module_methods'
	__BlueprintExtensions__/control.lua:96: in function <__BlueprintExtensions__/control.lua:93>
stack traceback:
	[C]: in function 'create_surface'
	__BlueprintExtensions__/modules/landfill.lua:53: in function 'compute_prototype_overrides'
	__BlueprintExtensions__/modules/landfill.lua:126: in function '?'
	__BlueprintExtensions__/control.lua:60: in function 'call_module_methods'
	__BlueprintExtensions__/control.lua:96: in function <__BlueprintExtensions__/control.lua:93>`

**Comment by dewiniaid** [comment]
This should be fixed in 0.4.6, which will be out later today.
