### ISSUE TITLE
Snap

### ISSUE THREAD

**Issue by gauchotche** [dewiniaid/BlueprintExtensions#7]
Blueprint Snap: While holding a prepared blueprint, use the numpad (by default) to snap the blueprint to a specific
corner or edge. This is useful if you can't fit a large blueprint entirely on screen and need to make it align
against some existing structure -- i.e. for tiling solar layouts.

Could you please explain further how to use this? Which keys do you refer by numpad?

**Comment by malkav73** [comment]
By numpad he means the numeric keypad on the far right of a standard QWERTY-style keyboard. If you're on a laptop, you probably don't have it.
